# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  profiles:
    # 注册配置文件
    active:
      - datasource

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# 日志配置
logging:
  level:
    com.beloved: debug

# MyBatis配置
mybatis:
  # 指定包别名
  type-aliases-package: com.beloved.**.entity
  # mapper映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 全局配置文件
  config-location: classpath:mybatis/mybatis-config.xml


