# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  profiles:
    # 注册配置文件
    active:
      - datasource

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
  # MyBatis 配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 指定包别名
  type-aliases-package: com.beloved.**.model.entity.**,;com.beloved.**.model.dto.**

# PageHelper分页插件
# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-%E5%88%86%E9%A1%B5%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D
pagehelper:
  # 数据库方言
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;

# token配置
token:
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  header: TOKEN
  token-prefix: 

  
bill:
  captcha-on-off: false
  captcha-type: gif
  captcha-expiration: 2