# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



# Spring配置
spring:
  profiles:
    # 注册配置文件
    active:
      - datasource

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 日志配置
logging:
  level:
    com.beloved: debug

# MyBatis配置
mybatis:
  # 指定包别名
  type-aliases-package: com.beloved.**.entity
  # mapper映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 全局配置文件
  config-location: classpath:mybatis/mybatis-config.xml


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  token_prefix: Bearer
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expire_time: 30